### ISSUE TITLE
Missing code TellerHohmeyer99

### ISSUE THREAD

**Issue by JensRestemeier** [erich666/jgt-code#13]
http://ftp.math.utah.edu/pub/tex/bib/toc/jgraphtools.html#4(3):1999
Seth Teller and Michael Hohmeyer   [Determining the Lines Through Four Lines](http://www.acm.org/jgt/papers/TellerHohmeyer99/)
supposedly had code included on the website, but wayback machine and google don't have anything at all. Are there any offline/cd-rom archives that may have the code?

**Comment by erich666** [comment]
Thanks. I've contacted Michael Hohmeyer via LinkedIn and hope he gets back to me. The paper itself is at https://people.csail.mit.edu/teller/pubs/TellerHohmeyerJGT2000.pdf

**Comment by erich666** [comment]
Michael has checked carefully and says he does not have the code. Seth passed away almost a decade ago. So I'm afraid this code is not something we'll be able to find. Closing.

**Comment by JensRestemeier** [comment]
That is sad news, but thanks for looking.
