### ISSUE TITLE
wrong files for Volume_12/Number_4/Hasselgren2007

### ISSUE THREAD

**Issue by moraxy** [erich666/jgt-code#2]
The files for [Volume_12/Number_4/Hasselgren2007](https://github.com/erich666/jgt-code/tree/master/Volume_12/Number_4/Hasselgren2007) are copies from [Volume_12/Number_4/Eisemann2007](https://github.com/erich666/jgt-code/tree/master/Volume_12/Number_4/Eisemann2007).

The correct files can be found in the supplements on [tandfonline.com](http://www.tandfonline.com/doi/suppl/10.1080/2151237X.2007.10129251)

**Comment by erich666** [comment]
Thanks much (and, d'oh). I'll fix this tonight.

**Comment by erich666** [comment]
Fixed, and I did the Taylor and Francis site one better: I extracted and cleaned up the shader code and put both in a text file. See https://github.com/erich666/jgt-code/tree/master/Volume_12/Number_4/Hasselgren2007
