### ISSUE TITLE
Outdated link for Lofstedt2005 in Readme

### ISSUE THREAD

**Issue by moraxy** [erich666/jgt-code#3]
The `code` link for
> Löfsted, Marta, and Tomas Akenine-Möller, "An Evaluation Framework for Ray-Triangle Intersection Algorithms," journal of graphics tools, 10(2):13-26, 2005.

points to the old path `Volume_10/Number_2/Lofsted2005` instead of the new one `Volume_10/Number_2/Lofstedt2005` (note the second `t`, committed in 58177bd016a42bd847fa480aa934e988d3727acd)

**Comment by erich666** [comment]
Thanks, and fixed.
