### ISSUE TITLE
N1 and N2 from where?

### ISSUE THREAD

**Issue by cpucoin** [erich666/jgt-code#6]
Hi,

in CONSTRUCT_INTERSECTION where do the values for N1 and N2 come from? e.g.

299   alpha = DOT(v1,N2) / DOT(v2,N2); \

**Comment by cpucoin** [comment]
jgt-code / Volume_08 / Number_1 / Guigue2003 / 

tri_tri_intersect.c

**Comment by erich666** [comment]
Sorry, I just noticed this - it must have flown past me some time ago in email. Anyway, N1 and N2 are the normals of the triangles 1 and 2. You can see these values get computed in the tri_tri_overlap_test_3d function. You get the direction vectors for two of the edges of the triangle and do a cross product to get the normal.
