### ISSUE TITLE
visual studio version

### ISSUE THREAD

**Issue by 1334738575** [erich666/jgt-code#8]
How to solve the problem that the code version is not compatible with my Visual Studio version

**Comment by erich666** [comment]
Sorry, just noticed this (I finally fixed my GIthub notifications so they work correctly). Right, you can't simply pull the whole repo into Visual Studio. This is a code repository from a wide variety of authors, developing on a wide variety of systems. It's expected that the code should be used as a starting point, and that different compilers may flag issues. So, I am closing this issue.

If you do find any compiler warnings or errors and there's a simple fix, please do let me know and I can fix these (or, better yet, you could submit a pull request that fixes them).

**Comment by 1334738575** [comment]
已收到，谢谢！
