### ISSUE TITLE
Triangle-triangle-intersection false positive?

### ISSUE THREAD

**Issue by RotateMe** [erich666/jgt-code#9]
Hi, 

I'm trying to use the lightning fast `tri_tri_intersect.c` to detect triangle-triangle intersections, but I'm getting weird false positives.

The following is a stand-alone code for one such case, two disjunct triangles, for which an intersection is detected:

```cpp
#include <iostream>
#include "tri_tri_intersect.c"

int main(int, char **)
{
    double v1[3];
    v1[0] = 22.374370052043300205468767671845853328704833984375;
    v1[1] = 29.5499517077955005106559838168323040008544921875;
    v1[2] = 0.69999999225848397177429660587222315371036529541015625;
    double v2[3];
    v2[0] = 22.355455793707999845310041564516723155975341796875;
    v2[1] = 29.591972981426099664759021834470331668853759765625;
    v2[2] = 0.600000003652259028541493535158224403858184814453125;
    double v3[3];
    v3[0] = 22.374370052043300205468767671845853328704833984375;
    v3[1] = 29.5499517077955005106559838168323040008544921875;
    v3[2] = 0.600000003652259028541493535158224403858184814453125;
    double v4[3];
    v4[0] = 22.355455793707999845310041564516723155975341796875;
    v4[1] = 29.591972981426099664759021834470331668853759765625;
    v4[2] = 0.8000000120163139882834002492018043994903564453125;
    double v5[3];
    v5[0] = 22.355455793707999845310041564516723155975341796875;
    v5[1] = 29.591972981426099664759021834470331668853759765625;
    v5[2] = 0.69999999225848397177429660587222315371036529541015625;
    double v6[3];
    v6[0] = 22.374370052043300205468767671845853328704833984375;
    v6[1] = 29.5499517077955005106559838168323040008544921875;
    v6[2] = 0.8000000120163139882834002492018043994903564453125;

    double start[3];
    double end[3];
    int coPlanar;
    const auto result = tri_tri_intersection_test_3d(v1, v2, v3, v4, v5, v6, &coPlanar, start, end);

    std::cout << "tri_tri_intersection_test_3d() returned " << result << std::endl;

    return 0;
}
```

The output is
```
tri_tri_intersection_test_3d() returned 1
```

The returned intersection edge is one of the edges of the two triangles. Here is a visualization of the two triangles and the returned intersection:
![image](https://user-images.githubusercontent.com/11388039/206750715-ba1bc192-857d-47ea-9034-bd7702cb2328.png)

Note that almost any truncation of the vertex coordinates will remedy this case.

I know this code is two decades old, but it's still the most referenced solution to this problem, and a lot of thought was put into it.

Maybe it's intsantly clear to someone what I'm doing wrong here?
Any input here is appreciated!

**Comment by erich666** [comment]
Sorry, just noticed this (I finally fixed my GIthub notifications so they work correctly). I've written the first author and hope for a response.

**Comment by erich666** [comment]
Hopefully this fix (merged) addresses this bug. Let us know, @RotateMe , if it doesn't.
